import Layout from "../../components/Layout"
import { getAllPostIds, getPostData } from "../../lib/post"
import utilStyle from "../../styles/utils.module.css"
import sanitize from "sanitize-html"
import Head from "next/head"


export async function getStaticPaths() {
  const paths = getAllPostIds()
  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({params}) {
  const postData = await getPostData(params.id)

  return {
    props: {
      postData,
    }
  }
}

export default function Post({postData}) {
  const __html = sanitize(postData.blogContentHTML, { allowedTags: false, allowedAttributes: false });
  return (
    <Layout>
      <Head>
        <title>{postData.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <h1 className={utilStyle.headingX1}>{postData.title}</h1>
        <div className={utilStyle.lightText}>
          {postData.date}
        </div>
        <div dangerouslySetInnerHTML={{__html}} />
      </article>
    </Layout>
  )
}